name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      working-directory: ../../
      run: |
          pwd
          make
    - name: make flcean
      working-directory: ../../
      run: make flcean
